name: ch06-node-sync

services:
  api:
    build:
      context: ./api
    command: npx nodemon src/server.js
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./api/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./api/package.json
